// Generated by CoffeeScript 1.3.3
(function() {
  var assert, driverOptions, webdriver;

  webdriver = require("wd");

  assert = require("assert");

  driverOptions = {
    browserName: "phantomjs"
  };

  driver.remote();

  driver.init(browserOptions, function(err, sessionid) {
    return console.log(sessionid);
  });

}).call(this);
