// Generated by CoffeeScript 1.3.3
(function() {
  var assert, driver, driverOptions, rootURL, webdriver;

  webdriver = require("wd");

  assert = require("assert");

  rootURL = "https://hapi-cms-dev.herokuapp.com/";

  driverOptions = {
    browserName: "phantomjs"
  };

  driver = webdriver.remote();

  driver.init(driverOptions, function(err, sessionid) {
    return driver.get(rootURL, function(err) {
      return driver.title(function(err, title) {
        console.log(title);
        return driver.quit();
      });
    });
  });

}).call(this);
